language: julia
os:
  - linux
#  - osx
julia:
  - 0.5
notifications:
  email:
    on_success: never
    on_failure: always
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'ENV["PYTHON"]=""; Pkg.add("PyCall"); Pkg.add("PyPlot"); using PyPlot;'
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.test("DynamicalBilliardsPlotting")'
